import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sileo";

export const metadata: Metadata = {
  title: "Tasker App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <Toaster position="top-center" theme="light" options={{fill: "#171717"}}/>
        {children}
      </body>
    </html>
  );
}
